import { Inter } from "next/font/google";
import "./globals.css";
import Login from "./components/page";
import Navbar from "./components/navbar";
import Modal from "./components/modal";
import ModalProvider, { ModalContext } from "./context/modelContext";
import ProductProvider from "./context/productContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          {false ? (
            <Login />
          ) : (
            <ModalProvider>
              <ProductProvider>
                <div>
                  <Navbar />
                  {children}
                </div>
              </ProductProvider>
            </ModalProvider>
          )}
        </div>
      </body>
    </html>
  );
}
