import { Inter } from "next/font/google";
import "./globals.css";
import Login from "./components/page";
import Navbar from "./components/navbar";
import Modal from "./components/modal";
import ModalProvider from "./context/modelContext";
import ProductProvider from "./context/productContext";
import OrderProvider from "./context/orderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task 2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          {false ? (
            <Login />
          ) : (
            <ModalProvider>
              <ProductProvider>
                <OrderProvider>
                  <div className="min-h-screen">
                    <Navbar />
                    {children}
                  </div>
                </OrderProvider>
              </ProductProvider>
            </ModalProvider>
          )}
        </div>
      </body>
    </html>
  );
}
